### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [20]:
def reverse_arrray_to_0(N):
    if type(N) == int and N > 0:
        x = np.arange(N-1, -1, -1)
        return x
    else:
        return 'Ввод неверен'


In [34]:
reverse_arrray_to_0(3)

array([2, 1, 0])

In [26]:
reverse_arrray_to_0('sdgb')

'Ввод неверен'

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
N=5

diag = np.diag(reverse_arrray_to_0(N))

print(diag)


[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [33]:
sum(np.diagonal(diag))

10

### Задание 3

Решите систему уравнений:
- 4x + 2y + z = 4
- x + 3y = 12
- 5y + 4z = -3

In [35]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [36]:
from numpy import linalg

In [37]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [38]:
np.allclose(np.dot(a, [ 0.46666667,  3.84444444, -5.55555556]), b)

True

### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.

Матрица в виде numpy array

In [40]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [41]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [42]:
def cosine(a, b):
    aleng = np.linalg.norm(a)
    bleng = np.linalg.norm(b)

    return np.dot(a, b)/(aleng * bleng)


In [64]:
#находим максимально близкий к 1
max_cosine = max(cosine(item, next_user_stats) for item in users_stats)
print(max_cosine)

#находим какой клиент обладает максимальной близостью
most_similarity = [item for item in users_stats if max_cosine == cosine(item, next_user_stats)]
print(*most_similarity)


0.9486832980505138
[0 1 1 0 0 0]


In [80]:
#Вариант через словарь, но тогда все с 0 в один схлопываются
new_users_stats = dict()

for item in users_stats:
    new_users_stats[cosine(item, next_user_stats)] = item
print(new_users_stats[max(new_users_stats.keys())])


[0 1 1 0 0 0]
